import Link from "next/link";
import { notFound } from "next/navigation";
import Card from "@/components/Card";
import Badge from "@/components/Badge";
import { FiArrowRight, FiCalendar, FiCheckCircle, FiChevronDown, FiClock, FiFileText, FiHelpCircle, FiMapPin, FiPhone, FiShield, FiUsers } from "react-icons/fi";

const policy = { id: "family-health-shield", provider: "CarePlus Insurance", name: "Family Health Shield Plus", number: "IC-FH-••••-4821", coverage: "₹15,00,000", members: "Priya Sharma, Arun Sharma, Meera Sharma, Kabir Sharma", validFrom: "16 Mar 2026", validTill: "15 Mar 2027", status: "Active" };
const details = [
  ["Coverage and benefits", ["Hospitalisation cover up to ₹15,00,000", "Pre and post-hospitalisation support", "Annual preventive health check-up", "Cashless care at participating network hospitals"]],
  ["Exclusions", ["Cosmetic procedures without medical necessity", "Treatment related to self-inflicted injury", "Experimental or unproven treatments"]],
  ["Waiting periods", ["Initial waiting period: 30 days", "Pre-existing conditions: 24 months", "Specified procedures: 24 months"]],
];
export default async function PolicyDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  if (id !== policy.id) notFound();
  return <div className="mx-auto flex max-w-7xl flex-col gap-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Link href="/patient/policies" className="inline-flex items-center gap-2 text-sm font-semibold text-teal-700 hover:text-teal-800"><FiArrowRight className="rotate-180" /> My policies</Link><p className="mt-5 text-sm font-medium text-teal-700">Synthetic demo policy</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">{policy.name}</h1><p className="mt-2 text-sm text-slate-500">{policy.provider} · Policy {policy.number}</p></div><Badge tone="green">{policy.status}</Badge></div>
    <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm leading-6 text-amber-900"><strong>Demo disclaimer:</strong> This page contains synthetic policy information only. It is not an insurance certificate, does not represent a real insurer relationship, and must not be used for healthcare or financial decisions.</div>
    <Card className="overflow-hidden"><div className="bg-teal-700 p-5 text-white sm:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-teal-100">Policy overview</p><h2 className="mt-2 text-xl font-semibold">Family protection cover</h2></div><FiShield className="text-2xl text-teal-100" /></div></div><div className="grid gap-5 p-5 sm:grid-cols-2 sm:p-6 lg:grid-cols-4"><div><p className="text-xs text-slate-500">Coverage amount</p><p className="mt-1 text-lg font-semibold text-slate-950">{policy.coverage}</p></div><div><p className="text-xs text-slate-500">Members covered</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold text-slate-900"><FiUsers className="text-teal-700" /> 4 members</p></div><div><p className="text-xs text-slate-500">Policy period</p><p className="mt-1 text-sm font-semibold text-slate-900">{policy.validFrom} – {policy.validTill}</p></div><div><p className="text-xs text-slate-500">Renewal</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold text-slate-900"><FiClock className="text-amber-600" /> 12 days</p></div></div></Card>
    <div className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]"><div className="flex flex-col gap-4">{details.map(([title, items]) => <Card key={title as string} className="p-5 sm:p-6"><h2 className="flex items-center gap-2 text-base font-semibold text-slate-950"><FiCheckCircle className="text-teal-700" />{title as string}</h2><ul className="mt-4 flex flex-col gap-3">{(items as string[]).map((item) => <li key={item} className="flex items-start gap-2 text-sm leading-6 text-slate-600"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-teal-600" />{item}</li>)}</ul></Card>)}<Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-950">Network hospitals</h2><p className="mt-1 text-sm text-slate-500">Synthetic network information near the demo account region.</p><div className="mt-4 flex items-center justify-between rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-white p-2 text-teal-700"><FiMapPin /></span><div><p className="text-sm font-semibold text-slate-800">Participating hospitals</p><p className="mt-1 text-xs text-slate-500">Cashless access shown for demonstration</p></div></div><FiChevronDown className="text-slate-400" /></div></Card></div>
    <div className="flex flex-col gap-4"><Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-950">Claim information</h2><p className="mt-2 text-sm leading-6 text-slate-500">For a planned admission, notify the synthetic insurer contact before treatment. For emergencies, notify within the demo timeline shown in your policy terms.</p><div className="mt-4 rounded-xl bg-teal-50 p-4 text-sm text-teal-900"><p className="font-semibold">Claim support hours</p><p className="mt-1 text-xs text-teal-800">Shown as demo information · 24/7 emergency line</p></div></Card><Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-950">Required documents</h2><ul className="mt-4 flex flex-col gap-3">{["Policy certificate", "Government photo ID", "Discharge summary", "Bills and prescriptions"].map((item) => <li key={item} className="flex items-center gap-3 text-sm text-slate-600"><FiFileText className="text-teal-700" />{item}</li>)}</ul></Card><Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-950">Renewal information</h2><p className="mt-2 text-sm leading-6 text-slate-500">Your synthetic policy is shown as renewing on 15 Mar 2027. Review benefits and premium details before renewal.</p><div className="mt-4 flex items-center gap-2 text-sm font-semibold text-amber-700"><FiCalendar /> Renewal due in 12 days</div></Card><Card className="p-5 sm:p-6"><h2 className="text-base font-semibold text-slate-950">Insurer contact</h2><p className="mt-2 text-sm text-slate-500">Synthetic support contact for this prototype only.</p><div className="mt-4 flex flex-col gap-3 text-sm"><span className="flex items-center gap-2 text-slate-700"><FiPhone className="text-teal-700" /> 1800-000-000</span><span className="flex items-center gap-2 text-slate-700"><FiHelpCircle className="text-teal-700" /> support@example.demo</span></div></Card></div></div>
  </div>;
}
