"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/cn";
import { FiActivity, FiFileText, FiGrid, FiHeart, FiMapPin, FiMessageCircle, FiSettings, FiShield } from "react-icons/fi";

type NavItem = { label: string; href: string; icon: React.ElementType };
const NAV_ITEMS: NavItem[] = [{ label: "Dashboard", href: "/patient", icon: FiGrid }, { label: "My Policies", href: "/patient/policies", icon: FiShield }, { label: "Hospitals", href: "/patient/hospitals", icon: FiHeart }, { label: "Claims", href: "/patient/claims", icon: FiActivity }, { label: "Documents", href: "/patient/documents", icon: FiFileText }, { label: "AI Assistant", href: "/patient/assistant", icon: FiMessageCircle }];
const SETTINGS_ITEM = { label: "Settings", href: "/patient/settings", icon: FiSettings };
function NavLink({ item, pathname }: { item: NavItem; pathname: string }) { const active = item.href === "/patient" ? pathname === "/patient" : pathname.startsWith(item.href); const Icon = item.icon; return <Link href={item.href} aria-current={active ? "page" : undefined} className={cn("group relative flex items-center gap-3 rounded-xl px-3.5 py-3 text-sm font-medium transition-all", active ? "bg-teal-700 text-white shadow-lg shadow-teal-900/15" : "text-slate-500 hover:bg-teal-50 hover:text-teal-800")}><Icon className={cn("size-[18px] transition-transform group-hover:scale-105", active ? "text-teal-50" : "text-slate-400 group-hover:text-teal-700")} />{item.label}{active && <span className="ml-auto size-1.5 rounded-full bg-white/80" />}</Link>; }
export default function Sidebar() { const pathname = usePathname(); return <aside className="flex min-h-screen w-72 shrink-0 flex-col border-r border-slate-200/80 bg-white"><div className="flex h-20 items-center gap-3 border-b border-slate-100 px-7"><div className="flex size-10 items-center justify-center rounded-xl bg-gradient-to-br from-teal-600 to-teal-800 text-xs font-bold text-white shadow-lg shadow-teal-900/20">IC</div><div><span className="block text-lg font-bold tracking-tight text-slate-950">InsureCare</span><span className="block text-[10px] font-semibold uppercase tracking-[0.16em] text-teal-700">Care, covered</span></div></div><div className="px-6 pb-2 pt-8 text-[10px] font-bold uppercase tracking-[0.18em] text-slate-400">Patient portal</div><nav aria-label="Main navigation" className="flex-1 px-4"><ul className="flex flex-col gap-1.5">{NAV_ITEMS.map((item) => <li key={item.href}><NavLink item={item} pathname={pathname} /></li>)}</ul></nav><div className="border-t border-slate-100 p-3"><NavLink item={SETTINGS_ITEM} pathname={pathname} /><div className="mx-3 mb-2 mt-5 rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-700">Need help?</p><p className="mt-1 text-[11px] leading-4 text-slate-500">Our care team is here for you.</p><Link href="/patient/assistant" className="mt-2 inline-block text-xs font-semibold text-teal-700">Contact support</Link></div></div></aside>; }
