"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/cn";
import { FiActivity, FiFileText, FiGrid, FiHeart, FiMapPin, FiMessageCircle, FiSettings, FiShield } from "react-icons/fi";

type NavItem = { label: string; href: string; icon: React.ElementType };
const NAV_ITEMS: NavItem[] = [{ label: "Dashboard", href: "/patient", icon: FiGrid }, { label: "My Policies", href: "/patient/policies", icon: FiShield }, { label: "Hospitals", href: "/patient/hospitals", icon: FiHeart }, { label: "Claims", href: "/patient/claims", icon: FiActivity }, { label: "Documents", href: "/patient/documents", icon: FiFileText }, { label: "AI Assistant", href: "/patient/assistant", icon: FiMessageCircle }];
const SETTINGS_ITEM = { label: "Settings", href: "/patient/settings", icon: FiSettings };
function NavLink({ item, pathname }: { item: NavItem; pathname: string }) { const active = item.href === "/patient" ? pathname === "/patient" : pathname.startsWith(item.href); const Icon = item.icon; return <Link href={item.href} aria-current={active ? "page" : undefined} className={cn("flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors", active ? "bg-teal-50 text-teal-800" : "text-slate-500 hover:bg-slate-50 hover:text-slate-900")}><Icon className={cn("size-[18px]", active ? "text-teal-700" : "text-slate-400")} />{item.label}</Link>; }
export default function Sidebar() { const pathname = usePathname(); return <aside className="flex min-h-screen w-64 shrink-0 flex-col border-r border-slate-200 bg-white"><div className="flex h-16 items-center gap-3 border-b border-slate-100 px-6"><div className="flex size-8 items-center justify-center rounded-lg bg-teal-700 text-xs font-bold text-white">IC</div><span className="text-lg font-bold tracking-tight text-slate-900">InsureCare</span></div><div className="px-6 pb-2 pt-7 text-[11px] font-semibold uppercase tracking-wider text-slate-400">Patient portal</div><nav aria-label="Main navigation" className="flex-1 px-3"><ul className="flex flex-col gap-1">{NAV_ITEMS.map((item) => <li key={item.href}><NavLink item={item} pathname={pathname} /></li>)}</ul></nav><div className="border-t border-slate-100 p-3"><NavLink item={SETTINGS_ITEM} pathname={pathname} /><div className="mx-3 mb-2 mt-5 rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-700">Need help?</p><p className="mt-1 text-[11px] leading-4 text-slate-500">Our care team is here for you.</p><Link href="/patient/assistant" className="mt-2 inline-block text-xs font-semibold text-teal-700">Contact support</Link></div></div></aside>; }
