import Link from "next/link";
import { notFound } from "next/navigation";
import Card from "@/components/Card";
import { claims, getClaim, statusClasses, statusDotClasses } from "../data";

function StatusBadge({ status }: { status: (typeof claims)[number]["status"] }) { return <span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs font-semibold ${statusClasses[status]}`}><span className={`size-1.5 rounded-full ${statusDotClasses[status]}`} />{status}</span>; }

export default async function ClaimDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const claim = claims.find((item) => item.id.toLowerCase() === id.toLowerCase());
  if (!claim) notFound();
  return <div className="mx-auto flex max-w-6xl flex-col gap-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div><Link href="/patient/claims" className="inline-flex items-center gap-2 text-sm font-semibold text-teal-700 hover:text-teal-800"><span aria-hidden="true">←</span> Back to claims</Link><p className="mt-5 text-sm font-medium text-teal-700">Synthetic demo claim</p><div className="mt-1 flex flex-col gap-3 sm:flex-row sm:items-center"><h1 className="text-2xl font-semibold tracking-tight text-slate-950 sm:text-3xl">Claim {claim.id}</h1><StatusBadge status={claim.status} /></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{claim.explanation}</p></div><div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-900">Synthetic data only<br />Not a real claim or payment record</div></div>
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="flex flex-col gap-6"><Card className="p-5 sm:p-6"><div className="mb-5"><h2 className="text-base font-semibold text-slate-950">Claim overview</h2><p className="mt-1 text-sm text-slate-500">Key details for this synthetic claim</p></div><div className="grid gap-x-6 gap-y-5 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Claim type</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.type}</p></div><div><p className="text-xs text-slate-500">Hospital / provider</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.provider}</p></div><div><p className="text-xs text-slate-500">Policy used</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.policy}</p></div><div><p className="text-xs text-slate-500">Date of treatment</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.treatmentDate}</p></div><div><p className="text-xs text-slate-500">Date submitted</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.submittedDate}</p></div><div><p className="text-xs text-slate-500">Last updated</p><p className="mt-1 text-sm font-semibold text-slate-900">{claim.updated}</p></div><div><p className="text-xs text-slate-500">Amount claimed</p><p className="mt-1 text-lg font-semibold text-slate-950">{claim.amountClaimed}</p></div><div><p className="text-xs text-slate-500">Approved / settled amount</p><p className="mt-1 text-lg font-semibold text-teal-700">{claim.amountApproved ?? "Pending"}</p></div></div></Card>
    <Card className="p-5 sm:p-6"><div className="mb-6"><h2 className="text-base font-semibold text-slate-950">Claim timeline</h2><p className="mt-1 text-sm text-slate-500">The current stage is highlighted below.</p></div><ol className="flex flex-col">{claim.timeline.map((item, index) => <li key={item.label} className="relative flex gap-4 pb-7 last:pb-0"><div className="flex flex-col items-center"><span className={`relative z-10 flex size-8 shrink-0 items-center justify-center rounded-full border-2 ${item.current ? "border-teal-600 bg-teal-600 text-white" : item.completed ? "border-teal-200 bg-teal-50 text-teal-700" : "border-slate-200 bg-white text-slate-300"}`}>{item.completed ? <span aria-hidden="true">✓</span> : <span aria-hidden="true">•</span>}</span>{index < claim.timeline.length - 1 && <span className={`mt-1 w-px flex-1 ${item.completed ? "bg-teal-200" : "bg-slate-200"}`} />}</div><div className="min-w-0 pt-1"><div className="flex flex-wrap items-center gap-2"><h3 className={`text-sm font-semibold ${item.current ? "text-teal-800" : "text-slate-900"}`}>{item.label}</h3>{item.current && <span className="rounded-full bg-teal-50 px-2 py-0.5 text-[11px] font-semibold text-teal-700">Current stage</span>}</div><p className="mt-1 text-xs font-medium text-slate-500">{item.date}</p><p className="mt-1 text-sm leading-6 text-slate-500">{item.note}</p></div></li>)}</ol></Card></div>
    <aside className="flex flex-col gap-6"><Card className="p-5"><div className="mb-4"><h2 className="text-base font-semibold text-slate-950">Required documents</h2><p className="mt-1 text-sm leading-5 text-slate-500">Upload action is UI-only in this prototype.</p></div><div className="flex flex-col divide-y divide-slate-100">{claim.documents.map((document) => <div key={document.name} className="flex items-center justify-between gap-3 py-3 first:pt-0 last:pb-0"><div className="flex min-w-0 items-center gap-2"><span aria-hidden="true" className="shrink-0 text-teal-700">▣</span><span className="truncate text-sm font-medium text-slate-800">{document.name}</span></div><span className={`shrink-0 text-xs font-semibold ${document.status === "Required" ? "text-orange-700" : "text-emerald-700"}`}>{document.status}</span></div>)}</div>{claim.documents.some((document) => document.status === "Required") && <button type="button" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-teal-800"><span aria-hidden="true">↑</span> Upload required document</button>}</Card><Card className="p-5"><h2 className="text-base font-semibold text-slate-950">Claim actions</h2><div className="mt-4 flex flex-col gap-2"><Link href="/patient/documents" className="inline-flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-700">View documents <span aria-hidden="true">↗</span></Link><Link href="/patient/policies" className="inline-flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-700">View policy <span aria-hidden="true">↗</span></Link><button type="button" className="inline-flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-700">Download claim summary <span aria-hidden="true">↓</span></button><Link href="/patient/assistant" className="inline-flex items-center justify-between rounded-lg border border-slate-200 px-3 py-2.5 text-sm font-semibold text-slate-700 hover:border-teal-200 hover:text-teal-700">Contact insurer <span aria-hidden="true">›</span></Link></div></Card></aside></div>
  </div>;
}

void Card;
void StatusBadge;
void getClaim;
