"use client";

import Link from 'next/link';
import { useMemo, useState } from 'react';
import { FiAlertCircle, FiArrowRight, FiCheckCircle, FiFilter, FiMapPin, FiSearch, FiShield, FiX } from 'react-icons/fi';
import Card from '@/components/Card';
import { DEMO_LOCATION, HOSPITALS, type Hospital } from './data';

export default function HospitalExplorer() {
  const [query, setQuery] = useState('');
  const [networkOnly, setNetworkOnly] = useState(false);
  const [emergencyOnly, setEmergencyOnly] = useState(false);
  const [schemeOnly, setSchemeOnly] = useState(false);
  const [specialty, setSpecialty] = useState('All specialties');
  const [distance, setDistance] = useState('Any distance');
  const [coverage, setCoverage] = useState<string | null>(null);

  const results = useMemo(() => HOSPITALS.filter((hospital) => {
    const text = `${hospital.name} ${hospital.locality} ${hospital.specialties.join(' ')}`.toLowerCase();
    const matchesQuery = !query || text.includes(query.toLowerCase());
    const matchesSpecialty = specialty === 'All specialties' || hospital.specialties.includes(specialty);
    const matchesNetwork = !networkOnly || hospital.network === 'Network';
    const matchesEmergency = !emergencyOnly || hospital.emergency;
    const matchesScheme = !schemeOnly || hospital.schemes.length > 0;
    const km = Number.parseFloat(hospital.distance);
    const matchesDistance = distance === 'Any distance' || (distance === 'Within 5 km' ? km <= 5 : km <= 10);
    return matchesQuery && matchesSpecialty && matchesNetwork && matchesEmergency && matchesScheme && matchesDistance;
  }), [query, specialty, networkOnly, emergencyOnly, schemeOnly, distance]);

  return <div className="mx-auto max-w-7xl">
    <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end">
      <div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Care access</p><h1 className="text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">Find a Hospital</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Discover nearby providers and understand how network and scheme availability may apply to your care.</p></div>
      <div className="flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-2 text-xs font-medium text-amber-900"><FiShield aria-hidden="true" /> Synthetic demo information</div>
    </div>

    <Card className="mb-6 p-4 sm:p-5"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="relative min-w-0 flex-1"><span className="sr-only">Search hospital or specialty</span><FiSearch aria-hidden="true" className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search hospital or specialty" className="h-11 w-full rounded-lg border border-slate-200 bg-slate-50 pl-10 pr-3 text-sm outline-none transition focus:border-teal-500 focus:ring-2 focus:ring-teal-100" /></label><div className="flex h-11 items-center gap-2 rounded-lg border border-slate-200 px-3 text-sm text-slate-700 lg:min-w-64"><FiMapPin aria-hidden="true" className="text-teal-700" /><span className="truncate">{DEMO_LOCATION}</span></div><button type="button" onClick={() => setQuery(query.trim())} className="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-teal-700 px-5 text-sm font-semibold text-white transition hover:bg-teal-800"><FiSearch aria-hidden="true" />Search</button></div><div className="mt-4 flex items-center gap-2 border-t border-slate-100 pt-4"><FiFilter aria-hidden="true" className="text-slate-400" /><span className="mr-1 text-xs font-semibold text-slate-700">Filters</span><select aria-label="Specialty" value={specialty} onChange={(event) => setSpecialty(event.target.value)} className="rounded-md border border-slate-200 bg-white px-2.5 py-2 text-xs text-slate-700"><option>All specialties</option><option>General medicine</option><option>Cardiology</option><option>Emergency care</option><option>Maternity</option><option>Primary care</option></select><select aria-label="Distance" value={distance} onChange={(event) => setDistance(event.target.value)} className="rounded-md border border-slate-200 bg-white px-2.5 py-2 text-xs text-slate-700"><option>Any distance</option><option>Within 5 km</option><option>Within 10 km</option></select><FilterButton label="Network only" active={networkOnly} onClick={() => setNetworkOnly(!networkOnly)} /><FilterButton label="Emergency" active={emergencyOnly} onClick={() => setEmergencyOnly(!emergencyOnly)} /><FilterButton label="Scheme available" active={schemeOnly} onClick={() => setSchemeOnly(!schemeOnly)} /></div></Card>

    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_320px]"><section><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold text-slate-800">{results.length} hospitals found</p><p className="text-xs text-slate-400">Sorted by distance · demo data</p></div><div className="flex flex-col gap-3">{results.map((hospital) => <HospitalResult key={hospital.id} hospital={hospital} onCoverage={() => setCoverage(hospital.id)} />)}{results.length === 0 && <Card className="p-8 text-center"><p className="font-semibold text-slate-800">No demo hospitals match these filters</p><p className="mt-1 text-sm text-slate-500">Try clearing a filter or searching for another specialty.</p></Card>}</div></section><DemoMap /></div>
    {coverage && <div role="status" className="fixed inset-x-4 bottom-4 z-20 mx-auto max-w-md rounded-xl border border-teal-200 bg-white p-4 shadow-xl sm:right-6 sm:left-auto"><div className="flex items-start gap-3"><div className="flex size-9 shrink-0 items-center justify-center rounded-full bg-teal-50 text-teal-700"><FiCheckCircle aria-hidden="true" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-slate-900">Demo coverage check</p><p className="mt-1 text-xs leading-5 text-slate-500">Network available · Scheme eligible · Coverage requires verification. No live insurance verification was performed.</p></div><button type="button" aria-label="Close coverage result" onClick={() => setCoverage(null)} className="text-slate-400 hover:text-slate-700"><FiX aria-hidden="true" /></button></div></div>}
  </div>;
}

function FilterButton({ label, active, onClick }: { label: string; active: boolean; onClick: () => void }) { return <button type="button" aria-pressed={active} onClick={onClick} className={`rounded-md border px-2.5 py-2 text-xs font-medium transition ${active ? 'border-teal-200 bg-teal-50 text-teal-800' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'}`}>{label}</button>; }

function HospitalResult({ hospital, onCoverage }: { hospital: Hospital; onCoverage: () => void }) { return <Card className="p-4 sm:p-5"><div className="flex flex-col gap-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-base font-bold text-slate-900">{hospital.name}</h2><span className="rounded-full bg-amber-50 px-2 py-1 text-[10px] font-semibold text-amber-800">Demo record</span></div><p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><FiMapPin aria-hidden="true" />{hospital.distance} · {hospital.locality}</p></div><span className={`inline-flex h-fit items-center gap-1 rounded-full px-2.5 py-1 text-xs font-semibold ${hospital.network === 'Network' ? 'bg-teal-50 text-teal-800' : 'bg-slate-100 text-slate-600'}`}>{hospital.network === 'Network' ? <FiCheckCircle aria-hidden="true" /> : <FiAlertCircle aria-hidden="true" />}{hospital.network}</span></div><div className="grid gap-3 border-y border-slate-100 py-3 text-xs sm:grid-cols-3"><Info label="Cashless" value={hospital.cashless ? 'Available (demo)' : 'Not listed'} positive={hospital.cashless} /><Info label="Emergency" value={hospital.emergency ? 'Available 24/7' : 'Not available'} positive={hospital.emergency} /><Info label="Demo rating" value={hospital.rating} /></div><div className="flex flex-wrap gap-2">{hospital.specialties.map((item) => <span key={item} className="rounded-md bg-slate-50 px-2.5 py-1.5 text-xs text-slate-600">{item}</span>)}</div><div className="flex flex-col gap-2 pt-1 sm:flex-row sm:justify-end"><Link href={`/patient/hospitals/${hospital.id}`} className="inline-flex items-center justify-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">View details <FiArrowRight aria-hidden="true" /></Link><button type="button" onClick={onCoverage} className="rounded-lg bg-teal-700 px-3 py-2 text-xs font-semibold text-white hover:bg-teal-800">Check coverage</button></div></div></Card>; }
function Info({ label, value, positive }: { label: string; value: string; positive?: boolean }) { return <div><p className="text-slate-400">{label}</p><p className={`mt-1 font-semibold ${positive ? 'text-teal-700' : 'text-slate-700'}`}>{value}</p></div>; }
function DemoMap() { return <Card className="h-fit overflow-hidden"><div className="border-b border-slate-100 p-4"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">Nearby care map</h2><p className="mt-1 text-xs text-slate-500">Synthetic location view</p></div><FiMapPin className="text-teal-700" aria-hidden="true" /></div></div><div className="relative h-64 overflow-hidden bg-[#e8f0ed]"><div className="absolute inset-0 opacity-60" style={{ backgroundImage: 'linear-gradient(32deg, transparent 47%, #c8d9d2 48%, #c8d9d2 50%, transparent 51%), linear-gradient(112deg, transparent 47%, #c8d9d2 48%, #c8d9d2 50%, transparent 51%)', backgroundSize: '92px 78px' }} /><div className="absolute left-[46%] top-[43%] flex size-12 items-center justify-center rounded-full border-4 border-white bg-teal-700 text-white shadow-lg"><FiMapPin aria-hidden="true" /></div><div className="absolute left-[24%] top-[25%] size-3 rounded-full bg-amber-500 ring-4 ring-white/80" /><div className="absolute right-[24%] top-[62%] size-3 rounded-full bg-teal-700 ring-4 ring-white/80" /><div className="absolute bottom-3 left-3 rounded-md bg-white/90 px-2 py-1 text-[10px] font-medium text-slate-600">Demo map · not live location</div></div></Card>; }
